### ISSUE TITLE
Ambiguity between `id-rsa-kem` and `id-kem-rsa`

### ISSUE THREAD

**Issue by ralienpp** [lamps-wg/rfc5990bis#2]
I'd like to bring this to your attention, because the difference is subtle, and unless you see both identifiers side by side - it is easy to mistake one for the other. Once you become aware of the difference, you have to read the text carefully to decide which OID is the one you want.

My understanding is:

- `id-kem-rsa OID ::= { is18033-2 key-encapsulation-mechanism(2) rsa(4) }` - this is the primitive defined in ISO 18033-2.
- `id-rsa-kem OID ::= { iso(1) member-body(2) us(840) rsadsi(113549) pkcs(1) pkcs-9(9) smime(16) alg(3) 14 }` - this is "RSA-KEM Key Transport Algorithm", i.e. it adds extra functionality on top of what the ISO defines, which is described in this RFC.

Wouldn't it be clearer if `id-rsa-kem` became `id-kem-rsa-kta` (for "key transport algorithm", or something like it)? This would disambiguate the terms.

Can you confirm that my understanding is correct? And can you explain what rule you rely on to decide whether what you need is id-kem-rsa or id-rsa-kem?

**Comment by russhousley** [comment]
Sadly, this is not new. To preserve alignment with RFC 5990, the same OIDs need to be used here.

**Comment by ralienpp** [comment]
Perhaps an alias could address this without breaking backward compatibility?

For example, define this `id-rsa-kem-kta ::= id-rsa-kem`, and then use the more verbose notation throughout the document. The underlying OID will be the same, existing implementations will continue to function. This is just a cosmetic change that improves readability by increasing the "distance" between the terms.

**Comment by russhousley** [comment]
This is an interesting thought.  I will consult with coauthors and the original authors of RFC 5990.

**Comment by russhousley** [comment]
On the spasm@ietf.org mail list, Joe Mandel suggested:

~~~
I'd like to make a suggestion to define an alias to improve readability and reduce confusion between id-rsa-kem and id-kem-rsa. For example, id-rsa-kem-spki ::= id-rsa-kem, since in the new structure it appears that id-rsa-kem only appears in the certificate subject public key information field. The OID would stay the same to not interfere with existing implementations.
~~~
